# Generated by Django 5.1.7 on 2025-06-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Lecturer', 'Lecturer'), ('Admin', 'Admin')], default='Admin', max_length=10),
        ),
    ]
