# Generated by Django 5.1.7 on 2025-06-07 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('webapp', '0004_alter_attendance_image_data_alter_attendance_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='image_data',
            field=models.ImageField(blank=True, help_text='Optional image data for attendance verification.', null=True, upload_to='attendance_images/'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(help_text='The class session for which attendance is recorded.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='webapp.classsession'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], help_text='Attendance status (Present, Absent, Late).', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(help_text='The student whose attendance is being recorded.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='webapp.student'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='course',
            field=models.ForeignKey(help_text='The course this session belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='webapp.course'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], help_text='Day of the week the session is held.', max_length=10),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='end_time',
            field=models.TimeField(help_text='End time of the session.'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='lecturer',
            field=models.ForeignKey(help_text='The lecturer conducting this session.', on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions_conducted', to='webapp.lecturer'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='room',
            field=models.CharField(help_text='Physical room or virtual link for the session.', max_length=50),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='start_time',
            field=models.TimeField(help_text='Start time of the session.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(help_text='Unique code for the course.', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(blank=True, help_text='The primary lecturer responsible for this course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to='webapp.lecturer'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(help_text='The course being enrolled in.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='webapp.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, help_text='Date of enrollment.'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(help_text='The student enrolled.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='webapp.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, help_text="Parent's email address.", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone_num',
            field=models.CharField(blank=True, help_text="Parent's phone number.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='%(app_label)s_%(class)s_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='%(app_label)s_%(class)s_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
