# Generated by Django 3.2.25 on 2025-06-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_attendance_image_data_alter_attendance_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='Day of the week the session is held.', max_length=10),
        ),
    ]
